### ISSUE TITLE
Question: Alternative syntax for dependencies

### ISSUE THREAD

**Issue by jp7677** [betsol/gulp-require-tasks#13]
Hi there,

Thanks a lot for your gulp module, it works really cool and makes everything a lot more readable.
One question though: if a task has no dependencies the format is really compact like your sample:

```
module.exports = function (gulp, callback) {
  return gulp.src('...')
    .pipe(compass())
    .pipe(gulp.dest('...'))
  ;
};
```

But if there is a dependency one has to switch to the module as object syntax. Would it be possible to support a syntax similar to:

```
module.dependencies = ['task1, 'task2']
module.exports = function (gulp, callback) {
  return gulp.src('...')
    .pipe(compass())
    .pipe(gulp.dest('...'))
  ;
};
```

This looks somehow a little bit cleaner than the module as object way. Though really don't know if this is possible. Thanks for your thoughts on this.

**Comment by slavafomin** [comment]
Hello @jp7677! Thank you for your interest in this module!

If you don't like the suggested syntax, e.g.:

``` js
// gulp-tasks/styles/build.js:

const compass = require('compass');

module.exports = {
  dep: ['styles:clean', 'icons:build'],
  fn: function (gulp, callback) {
    return gulp.src('...')
      .pipe(compass())
      .pipe(gulp.dest('...'))
    ;
  }
};
```

You could try to use the following:

``` js
// gulp-tasks/styles/build.js:

const compass = require('compass');

exports.dep = ['styles:clean', 'icons:build'];
exports.fn = function (gulp, callback) {
    return gulp.src('...')
      .pipe(compass())
      .pipe(gulp.dest('...'))
    ;
  };
```

It's an alternative syntax for defining Node modules and it should work right away.

**Comment by jp7677** [comment]
Hi @slavafomin Perfectly, thanks a lot!
