### ISSUE TITLE
Possible to retrieve values from dependencies?

### ISSUE THREAD

**Issue by nessthehero** [betsol/gulp-require-tasks#15]
Using the following syntax:

````
const compass = require('compass');
 
module.exports = {
  dep: ['styles:clean', 'icons:build'],
  fn: function (gulp, callback) {
    return gulp.src('...')
      .pipe(compass())
      .pipe(gulp.dest('...'))
    ;
  }
};
````

is there a way to declare a variable or an object in the dependencies and have it come through to the function being declared afterwards?

Here's my code for example. I am trying to compile templates from assemble.io.

gulpfile.js
````
const gulp = require('gulp');
require('gulp-require-tasks')();

gulp.task('build', [
	'assemble'
]);

gulp.task('default', ['build']);
````

assemble-load.js
````
'use strict';

module.exports = (gulp, callback) => {
	const path = require('path');
	const assemble = require('assemble')();

	assemble.helper(require(path.join(__dirname, '/../app/assemble/helpers/helpers.js')));

	assemble.partials([
		path.join(__dirname, '/../app/assemble/includes/*.hbs'),
		path.join(__dirname, '/../app/assemble/modules/*.hbs'),
		path.join(__dirname, '/../app/assemble/partials/*.hbs')
	]);
	assemble.layouts(path.join(__dirname, '/../app/assemble/layouts/*.hbs'));
	assemble.data(path.join(__dirname, '/../app/assemble/fixtures/*.json'));
  	assemble.pages(path.join(__dirname, '/../app/assemble/*.hbs'));

	return assemble;

	callback();
}
````

assemble.js
````
'use strict';

module.exports = {
	dep: ['assemble-load'],
	fn: function (gulp, callback) {
		
		const path = require('path');		
		const assemble = require('assemble')();
		const extname = require('gulp-extname');

		return assemble.toStream('pages')
			.pipe(assemble.renderFile())
			.pipe(extname())
			.pipe(assemble.dest('../app'));

	}
}
````

I had this working earlier in a more combined syntax, I'm just trying to get it into this fancy syntax, so I know my paths and such are correct. Also, outputting `assemble` to the console in assemble-load.js I can see all my templates and partials in the object. If I output `assemble` in assemble.js, it's just an empty object.

I'm not super solid on ES6 so I would appreciate code examples over vocabulary words. Thanks!

**Comment by slavafomin** [comment]
Hello! Thank you for your interest in this module!

> is there a way to declare a variable or an object in the dependencies and have it come through to the function being declared afterwards?

If we are talking about `dep` and `fn` here then it's not working that way.

The `dep` is the list of Gulp tasks which must be completed before the `fn` is called. You can't use it to pass some arguments to the `fn` function.

However, if you need to pass something externally to the `fn` function, you could either use the `arguments` option of this module or use Node.js global variable.

Have I answered your question? If not, please clarify.

**Comment by nessthehero** [comment]
Your answer makes sense.

What I ended up being able to do was add something to the `gulp` value that I'm passing around, since gulp is somewhat global. That solved my issue.

Thanks for taking the time to answer my question! I'll go ahead and close this issue.
