### ISSUE TITLE
Register tasks with the name of directories

### ISSUE THREAD

**Issue by 7studio** [betsol/gulp-require-tasks#16]
Hi Slava,

First of all, thank you very much for your useful gulp plugin :D

I would like to suggest a new feature. 
Here is my case: 

I have these sub-directories to structure my tasks:
```
gulp/
  install/
    task1.js
    task2.js
  process/
  	task1.js
    task2.js
    task3.js
  build/
```
and this `gulpfile.js`:
```
var gulp = require('gulp');
var tasksLoader = require('gulp-require-tasks');
var runSequence = require('run-sequence');

tasksLoader({
    path: process.cwd() + '/gulp/tasks',
    gulp: gulp
});

gulp.task('install', ['install:task1', 'install:task2']);

gulp.task('process', function(done) {
    runSequence(
        ['process:task1'],
        ['process:task2'],
        ['process:task3'],
        done
    );
});
```

It could be very very useful if we could find a way to register tasks with the same
name than directories without creating them in the `gulpfile.js` or having files
with these names into the `gulp/` directory.

I thought that having an `index.js` in the directories could register a gulp task with the name
of these directories. 

Example:
```
gulp/
  install/
  	index.js
    task1.js
    task2.js
  process/
  	index.js
  build/
```
will register these tasks:

* install
* install:task1
* install:task2
* process

What do you think about this idea?

I would be happy to help you through a PR if you want to.
Xavier.

**Comment by slavafomin** [comment]
Hello! Thank you for your interest in this module!

Actually, it's a solid idea, I was thinking about it myself. However, my time is scarce at the moment, but I will keep an eye on it.
