### ISSUE TITLE
arguments is an empty object in on.('finish') callback

### ISSUE THREAD

**Issue by koreem** [betsol/gulp-require-tasks#20]
Seems that the arguments is empty in the on finish callback, or am I doing something wrong here?

```
var chug = require('gulp-chug');

module.exports = function (gulp, arguments, callback) {
    return gulp.src( arguments.path + 'gulpfile.js' )
        .pipe( chug( {
                    tasks: [ 'build' ],
                    args:   [ '--ip=' + arguments.ip, '--api=' + arguments.api , '--https=' + arguments.https]}) )
        .on('finish', function() {
            console.log(arguments) //arguments is {} here (empty)
            gulp.src([arguments.path + '/dist/**/*'])
            .pipe(gulp.dest('a-destination-name'));
        });
};

```

**Comment by koreem** [comment]
I solved the issue. Re declared the variable inside the function.

```
var _arguments = arguments
```

**Comment by slavafomin** [comment]
Hello! Thank you for your interest in this module!

I've deprecated usage of `arguments` today. Please [read here for alternative solution](https://github.com/betsol/gulp-require-tasks#passing-data-to-the-task-function).

By the way, the `arguments` is a [reserved variable](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments) in JavaScript. You should never name your function argument as `arguments`.

**Comment by koreem** [comment]
Thanks!
