### ISSUE TITLE
Multiple tasks in a single file?

### ISSUE THREAD

**Issue by Cristy94** [betsol/gulp-require-tasks#21]
Can you still have multiple tasks in the same file? Sometimes you want to have multiple tasks in one file because they might all use some shared variables declared at the top of the file, and the tasks might be logically-related so it makes sense to have them in the same file.

**Comment by slavafomin** [comment]
Hello! Thank you for your interest in this module!

However, I'm afraid it's not possible directly. However, you can always access `gulp` instance from inside the task file, therefore you can add tasks to it using normal Gulp syntax if you really want to do this.

However, I would suggest to extract common variables either into separate file, or define them as global variables in the Gulpfile. the same goes for utility functions.

**Comment by slavafomin** [comment]
I'm so sorry, but this extension is [deprecated](https://github.com/betsol/gulp-require-tasks#deprecation-notice) and archived now. You can still use it in legacy projects with **Gulp 3**, but I'm not planning to fix the issues or add new features, as well as merging any PRs.

🚀 Please, consider migrating to [Gulp 4][gulp-4] with [Gulp Hub][gulp-hub] instead.

❤️ Thank you for using this library in the past. I wish you the best of luck with your projects!

  [gulp-4]:   https://gulpjs.com/
  [gulp-hub]: https://github.com/frankwallis/gulp-hub/tree/registry-init
