### ISSUE TITLE
Load tasks from multiple directories

### ISSUE THREAD

**Issue by koreem** [betsol/gulp-require-tasks#22]
Is it somehow possible to use multiple path directories for example with glob patterns?
Lets say I have multiple modules with their own tasks directory. 

```
taskLoader({
    gulp: gulp,
    path: __dirname + '/modules/**/tasks',
    passCallback: false
});
```

**Comment by lrenhrda** [comment]
This would be great to have. I'm currently working on a custom static site generator using Gulp, and I'd like to be able to let a site define custom tasks to run at build, in addition to the standard set of tasks that the site generator has.

**Comment by slavafomin** [comment]
Hello! Thank you for your interest in this module!

This looks like a really good feature to have, I will try to look into it when time permits.

**Comment by slavafomin** [comment]
I'm so sorry, but this extension is [deprecated](https://github.com/betsol/gulp-require-tasks#deprecation-notice) and archived now. You can still use it in legacy projects with **Gulp 3**, but I'm not planning to fix the issues or add new features, as well as merging any PRs.

🚀 Please, consider migrating to [Gulp 4][gulp-4] with [Gulp Hub][gulp-hub] instead.

❤️ Thank you for using this library in the past. I wish you the best of luck with your projects!

  [gulp-4]:   https://gulpjs.com/
  [gulp-hub]: https://github.com/frankwallis/gulp-hub/tree/registry-init
