### ISSUE TITLE
The path option documentation is not clear

### ISSUE THREAD

**Issue by SchnWalter** [betsol/gulp-require-tasks#24]
The available information for the `path` option is not clear enough. The default value is `process.cwd() + '/gulp-tasks'` and not `./gulp-tasks`.

When trying to import tasks from a relative directory, gulp will throw an error because it looks for a directory that is relative to the module directory and not the project root where `gulpfile.js` is located.

To reproduce the issue, try to import tasks from a relative path, like:
```
require('gulp-require-tasks')({
  path: './my-gulp-tasks'
});
```

**Comment by slavafomin** [comment]
I'm so sorry, but this extension is [deprecated](https://github.com/betsol/gulp-require-tasks#deprecation-notice) and archived now. You can still use it in legacy projects with **Gulp 3**, but I'm not planning to fix the issues or add new features, as well as merging any PRs.

🚀 Please, consider migrating to [Gulp 4][gulp-4] with [Gulp Hub][gulp-hub] instead.

❤️ Thank you for using this library in the past. I wish you the best of luck with your projects!

  [gulp-4]:   https://gulpjs.com/
  [gulp-hub]: https://github.com/frankwallis/gulp-hub/tree/registry-init
