### ISSUE TITLE
Pass options to white/blacklist files in tasks directory

### ISSUE THREAD

**Issue by kapooostin** [betsol/gulp-require-tasks#25]
It would be nice to keep some helpers or test along with tasks and exclude them from files `gulp` will try to use as tasks.

https://github.com/troygoode/node-require-directory supports both ways of filtering, so it would be a matter of passing through and merging options. If you are interested in it I could try to make a pull request.

**Comment by slavafomin** [comment]
I'm so sorry, but this extension is [deprecated](https://github.com/betsol/gulp-require-tasks#deprecation-notice) and archived now. You can still use it in legacy projects with **Gulp 3**, but I'm not planning to fix the issues or add new features, as well as merging any PRs.

🚀 Please, consider migrating to [Gulp 4][gulp-4] with [Gulp Hub][gulp-hub] instead.

❤️ Thank you for using this library in the past. I wish you the best of luck with your projects!

  [gulp-4]:   https://gulpjs.com/
  [gulp-hub]: https://github.com/frankwallis/gulp-hub/tree/registry-init
