### ISSUE TITLE
Share configuration variables across all task files

### ISSUE THREAD

**Issue by reecefowell** [betsol/gulp-require-tasks#5]
how does one pass in configurations stored in some variable?

Vars do not seem to be shared across multiple gulpjs files, but I store them in one place to avoid repeating things and also to keep the piping clean.

**Comment by slavafomin** [comment]
You should either use global variables, supported by Node.js, or extract all your configuration into a separate module file and `require()` it in each of your task files.

I'm using global variables for this:

``` js
// gulpfile.js
global.SRC_PATH = __dirname + '/assets';
global.TARGET_PATH = __dirname + '/.public';
global.dist = false;
```
