### ISSUE TITLE
Provide support for modules that change Gulp's API

### ISSUE THREAD

**Issue by digitaldonkey** [betsol/gulp-require-tasks#6]
Actually the loader is not working for anything which extends the gulp task Object somehow like: 

`gulp = plug.help(require('gulp'));`

See: https://www.npmjs.com/package/gulp-help

I could [hack](https://github.com/digitaldonkey/gulp-require-tasks/commit/baa850b72f86b3a229f73d5d87af65b28cb96539) your module to support gulp help, but maybe you have a more generic idea. Because my hack now depends on gulp-help.

**Comment by slavafomin** [comment]
Hello @digitaldonkey! Thank you for your interest in this module!

I'm sorry for a late reply, we have very limited resources right now.

My generic idea is that it's not a good thing to change the interface of the third-party module, like `gulp-help` does with `gulp`. I think `gulp-help` should provide some other non-obtrusive means to define help messages for tasks.

Hey, @chmontgomery what do you think about this?

Right now, I have no good ideas of how we can make it to work without creating a complex mess of Gulp's API. Of course I can extract Gulp's task definition into a separate function, that you will be able to re-define in your project's code, but I'm not sure if this complexity is worth it.

**Comment by chmontgomery** [comment]
it's true, `gulp-help` is purposefully obtrusive, changing gulp's underlying API. If it were me, I wouldn't write any crazy code in `gulp-require-tasks` just to support it.

That said, [gulp-help v4.0](https://github.com/chmontgomery/gulp-help/tree/gulp4) (which was re-written for gulp v4) does _not_ change the underlying API. So going forward, `gulp-require-tasks` should work without problems (assuming it also supports gulp v4)

**Comment by slavafomin** [comment]
Thank you @chmontgomery, that makes sense. Let's then wait for Gulp 4 release and see what we can do about this.

For now, I'm not planning to implement any workarounds, considering the complexity of the integration.

@digitaldonkey if you have any good thoughts about it, or some alternatives, please let me know. I'm not closing this for now.

**Comment by digitaldonkey** [comment]
I just forked and hacked in order to get my project running. I think it's kind of required for certain types  of modules to hook into the process before gulp (like this module). And I wouldn't recommend to fix for gulp-help only, but try to find a general way on how the params can be transformed in order to have a general approach. 
I will watch this issue and may be able to help testing if you decide to implement.

**Comment by slavafomin** [comment]
Okay then, if this issue will get enough attention, we will look into it. For now, I will have to preserve our resources.

Cheers!
