### ISSUE TITLE
Support for babel files

### ISSUE THREAD

**Issue by schoenwaldnils** [betsol/gulp-require-tasks#7]
Currently `.babel.js` files are getting ignored.
Is there a possible workaround?

**Comment by slavafomin** [comment]
Hello!

I'm not familiar with this file format, could you elaborate please?

If the file conforms to the [documented format](https://github.com/betsol/gulp-require-tasks#task-module-format) it should work fine, however, if you need it to work with some other format, you should create a feature request with comprehensive description of required functionality. Then we will be able to discuss it further.

Cheers!

**Comment by schoenwaldnils** [comment]
Hi, 

this is for using ES2015 in your gulpfile.
A better explenation here: https://markgoodyear.com/2015/06/using-es6-with-gulp/

**Comment by slavafomin** [comment]
Well, I see.

I will look into it on first occasion. ES2015 is definitely the future, so I will make it a priority.

**Comment by schoenwaldnils** [comment]
Hi there, are there any updates on this enhancement?
I'm working a lot with gulp lately, and my gulpfile is way to big :D

**Comment by LNSD** [comment]
@schoenwaldnils I'm not sure what `.babel.js` files are talking about, but I'm using a babel gulpfile (`gulpfile.babel.js`) and this module is working well. :+1:

**Comment by schoenwaldnils** [comment]
@LNSD are your required files for different tasks also written in ES6? I think that was my problem.

**Comment by LNSD** [comment]
Yes, they use ES6 syntax (for example I'm using `import` in stead of `require()`). The task files are not named `whatever.babel.js`. And it's working. 

I've tried to use the `export default function (gulp) {...}`, but it doesn't work; so I kept the ES5 `modules.export = function (gulp) {...}`. I think is related to the way that this module import/requires tasks.

I hope I've helped.

**Comment by schoenwaldnils** [comment]
@LNSD I tried using it again, and the way you describe it, it works.
I just wonder why `export default function` doesn't work. If I want to write ES6, I want to use it all the way ^^

**Comment by markotom** [comment]
@LNSD @schoenwaldnils 

This library uses `node-require-directory` to load tasks files. I recently sent this pull request https://github.com/troygoode/node-require-directory/pull/31 to add support to ES6 exports.

I hope this helps eventually with this library!

**Comment by slavafomin** [comment]
Thank you for pinpointing the problem @markotom, I've commented on your PR. I will be glad if it will be accepted, it will make default exports possible with this module as well.

**Comment by kapooostin** [comment]
You should `export const fn = (gulp, callback)...` for a main task and `export const deps = []` for dependent tasks.

**Comment by schoenwaldnils** [comment]
@kapooostin are you sure you're in the correct issue? export does not work at all (since I tested it the last time)

**Comment by kapooostin** [comment]
Yep, I'm using it right now. It works because we have this https://github.com/betsol/gulp-require-tasks#module-as-an-object
