### ISSUE TITLE
__dirname + '/tasks' is not default value of path parameter

### ISSUE THREAD

**Issue by armenbadalyan** [betsol/gulp-require-tasks#8]
First of all thank you for this useful module.

I've noticed that when calling 

```
gulpRequireTasks({});
```

 default path parameter resolves to node_modules/gulp-require-tasks/tasks folder. This is not too big of an issue since we can initialize it with

```
gulpRequireTasks({
  // Pass any options to it. Please see below.
  path: __dirname + '/tasks' // This is default
});
```

But still I think it would make more sense to default it __dirname + '/tasks' . Also "// this is default" comment is misleading.

Thanks!

**Comment by slavafomin** [comment]
That makes sense, thanks for an observation. I will keep it in mind. PR is welcome for this issue.

**Comment by slavafomin** [comment]
Hey @armenbadalyan ! Thanks again for posting this issue. I've fixed it as of now. However, the name of the default directory is changed to `gulp-tasks/` for more clarity. Feel free to check out version `1.0.5`!

Thank you for your patience.
